package com.example.demo.model;

import java.io.Serializable;

public class Customer implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers.customer_id
     *
     * @mbg.generated Sun Jun 20 09:47:15 CST 2021
     */
    private Integer customerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers.name
     *
     * @mbg.generated Sun Jun 20 09:47:15 CST 2021
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table customers
     *
     * @mbg.generated Sun Jun 20 09:47:15 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.customer_id
     *
     * @return the value of customers.customer_id
     *
     * @mbg.generated Sun Jun 20 09:47:15 CST 2021
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers
     *
     * @mbg.generated Sun Jun 20 09:47:15 CST 2021
     */
    public Customer withCustomerId(Integer customerId) {
        this.setCustomerId(customerId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.customer_id
     *
     * @param customerId the value for customers.customer_id
     *
     * @mbg.generated Sun Jun 20 09:47:15 CST 2021
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.name
     *
     * @return the value of customers.name
     *
     * @mbg.generated Sun Jun 20 09:47:15 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers
     *
     * @mbg.generated Sun Jun 20 09:47:15 CST 2021
     */
    public Customer withName(String name) {
        this.setName(name);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.name
     *
     * @param name the value for customers.name
     *
     * @mbg.generated Sun Jun 20 09:47:15 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers
     *
     * @mbg.generated Sun Jun 20 09:47:15 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", customerId=").append(customerId);
        sb.append(", name=").append(name);
        sb.append("]");
        return sb.toString();
    }
}