package com.example.demo.model;

import java.io.Serializable;

public class Service implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column services.service_id
     *
     * @mbg.generated Sun Jun 20 09:47:15 CST 2021
     */
    private Integer serviceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column services.name
     *
     * @mbg.generated Sun Jun 20 09:47:15 CST 2021
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table services
     *
     * @mbg.generated Sun Jun 20 09:47:15 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column services.service_id
     *
     * @return the value of services.service_id
     *
     * @mbg.generated Sun Jun 20 09:47:15 CST 2021
     */
    public Integer getServiceId() {
        return serviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table services
     *
     * @mbg.generated Sun Jun 20 09:47:15 CST 2021
     */
    public Service withServiceId(Integer serviceId) {
        this.setServiceId(serviceId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column services.service_id
     *
     * @param serviceId the value for services.service_id
     *
     * @mbg.generated Sun Jun 20 09:47:15 CST 2021
     */
    public void setServiceId(Integer serviceId) {
        this.serviceId = serviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column services.name
     *
     * @return the value of services.name
     *
     * @mbg.generated Sun Jun 20 09:47:15 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table services
     *
     * @mbg.generated Sun Jun 20 09:47:15 CST 2021
     */
    public Service withName(String name) {
        this.setName(name);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column services.name
     *
     * @param name the value for services.name
     *
     * @mbg.generated Sun Jun 20 09:47:15 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table services
     *
     * @mbg.generated Sun Jun 20 09:47:15 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", serviceId=").append(serviceId);
        sb.append(", name=").append(name);
        sb.append("]");
        return sb.toString();
    }
}