package com.example.demo.model;

import java.io.Serializable;

public class SubscriptionKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscriptions.service_id
     *
     * @mbg.generated Sun Jun 20 09:47:15 CST 2021
     */
    private Integer serviceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscriptions.customer_id
     *
     * @mbg.generated Sun Jun 20 09:47:15 CST 2021
     */
    private Integer customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table subscriptions
     *
     * @mbg.generated Sun Jun 20 09:47:15 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscriptions.service_id
     *
     * @return the value of subscriptions.service_id
     *
     * @mbg.generated Sun Jun 20 09:47:15 CST 2021
     */
    public Integer getServiceId() {
        return serviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscriptions
     *
     * @mbg.generated Sun Jun 20 09:47:15 CST 2021
     */
    public SubscriptionKey withServiceId(Integer serviceId) {
        this.setServiceId(serviceId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscriptions.service_id
     *
     * @param serviceId the value for subscriptions.service_id
     *
     * @mbg.generated Sun Jun 20 09:47:15 CST 2021
     */
    public void setServiceId(Integer serviceId) {
        this.serviceId = serviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscriptions.customer_id
     *
     * @return the value of subscriptions.customer_id
     *
     * @mbg.generated Sun Jun 20 09:47:15 CST 2021
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscriptions
     *
     * @mbg.generated Sun Jun 20 09:47:15 CST 2021
     */
    public SubscriptionKey withCustomerId(Integer customerId) {
        this.setCustomerId(customerId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscriptions.customer_id
     *
     * @param customerId the value for subscriptions.customer_id
     *
     * @mbg.generated Sun Jun 20 09:47:15 CST 2021
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscriptions
     *
     * @mbg.generated Sun Jun 20 09:47:15 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", serviceId=").append(serviceId);
        sb.append(", customerId=").append(customerId);
        sb.append("]");
        return sb.toString();
    }
}