package com.example.demo.mapper;

import com.example.demo.model.Service;
import com.example.demo.model.ServiceExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.session.RowBounds;

public interface ServiceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table services
     *
     * @mbg.generated Sun Jun 20 09:47:15 CST 2021
     */
    long countByExample(ServiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table services
     *
     * @mbg.generated Sun Jun 20 09:47:15 CST 2021
     */
    int deleteByExample(ServiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table services
     *
     * @mbg.generated Sun Jun 20 09:47:15 CST 2021
     */
    @Delete({
        "delete from services",
        "where service_id = #{serviceId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer serviceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table services
     *
     * @mbg.generated Sun Jun 20 09:47:15 CST 2021
     */
    @Insert({
        "insert into services (name)",
        "values (#{name,jdbcType=VARCHAR})"
    })
    @SelectKey(statement="CALL IDENTITY()", keyProperty="serviceId", before=false, resultType=Integer.class)
    int insert(Service record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table services
     *
     * @mbg.generated Sun Jun 20 09:47:15 CST 2021
     */
    int insertSelective(Service record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table services
     *
     * @mbg.generated Sun Jun 20 09:47:15 CST 2021
     */
    List<Service> selectByExampleWithRowbounds(ServiceExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table services
     *
     * @mbg.generated Sun Jun 20 09:47:15 CST 2021
     */
    List<Service> selectByExample(ServiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table services
     *
     * @mbg.generated Sun Jun 20 09:47:15 CST 2021
     */
    @Select({
        "select",
        "service_id, name",
        "from services",
        "where service_id = #{serviceId,jdbcType=INTEGER}"
    })
    //@ResultMap("com.example.demo.mapper.ServiceMapper.BaseResultMap")
    Service selectByPrimaryKey(Integer serviceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table services
     *
     * @mbg.generated Sun Jun 20 09:47:15 CST 2021
     */
    int updateByExampleSelective(@Param("record") Service record, @Param("example") ServiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table services
     *
     * @mbg.generated Sun Jun 20 09:47:15 CST 2021
     */
    int updateByExample(@Param("record") Service record, @Param("example") ServiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table services
     *
     * @mbg.generated Sun Jun 20 09:47:15 CST 2021
     */
    int updateByPrimaryKeySelective(Service record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table services
     *
     * @mbg.generated Sun Jun 20 09:47:15 CST 2021
     */
    @Update({
        "update services",
        "set name = #{name,jdbcType=VARCHAR}",
        "where service_id = #{serviceId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Service record);
}