package com.example.demo.mapper;

import com.example.demo.model.SubscriptionExample;
import com.example.demo.model.SubscriptionKey;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SubscriptionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscriptions
     *
     * @mbg.generated Sun Jun 20 09:47:15 CST 2021
     */
    long countByExample(SubscriptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscriptions
     *
     * @mbg.generated Sun Jun 20 09:47:15 CST 2021
     */
    int deleteByExample(SubscriptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscriptions
     *
     * @mbg.generated Sun Jun 20 09:47:15 CST 2021
     */
    @Delete({
        "delete from subscriptions",
        "where service_id = #{serviceId,jdbcType=INTEGER}",
          "and customer_id = #{customerId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(SubscriptionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscriptions
     *
     * @mbg.generated Sun Jun 20 09:47:15 CST 2021
     */
    @Insert({
        "insert into subscriptions (service_id, customer_id)",
        "values (#{serviceId,jdbcType=INTEGER}, #{customerId,jdbcType=INTEGER})"
    })
    int insert(SubscriptionKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscriptions
     *
     * @mbg.generated Sun Jun 20 09:47:15 CST 2021
     */
    int insertSelective(SubscriptionKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscriptions
     *
     * @mbg.generated Sun Jun 20 09:47:15 CST 2021
     */
    List<SubscriptionKey> selectByExampleWithRowbounds(SubscriptionExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscriptions
     *
     * @mbg.generated Sun Jun 20 09:47:15 CST 2021
     */
    List<SubscriptionKey> selectByExample(SubscriptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscriptions
     *
     * @mbg.generated Sun Jun 20 09:47:15 CST 2021
     */
    int updateByExampleSelective(@Param("record") SubscriptionKey record, @Param("example") SubscriptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscriptions
     *
     * @mbg.generated Sun Jun 20 09:47:15 CST 2021
     */
    int updateByExample(@Param("record") SubscriptionKey record, @Param("example") SubscriptionExample example);
}